name: ci
on: [push, pull_request]
jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: install bun
        run: npm install -g bun

      - name: install dependencies
        run: bun i

      - name: build
        run: bun run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}"
          CLERK_SECRET_KEY: "${{secrets.CLERK_SECRET_KEY}}"
          DATABASE_URL: "${{secrets.DATABASE_URL}}"

      - name: lint
        run: bun run lint
